# CI de Nível 012 - Disparo atomático em períodos definidos

# nome que vai aparecer na execução de pipe
name: 'Execução Agendada'

# Triggers ou gatilhos de execução
  # gatilho de execução agendada = schedule
on:
  schedule:
    - cron: '35 11 * * 1'

jobs:
  # descrição dos jobs
  e2e-tests:
    # maquina onde vai executar o job
    runs-on: ubuntu-latest
    # passo a passo das ececuções do job
    # set de timeZone
    env: 
      TZ:  America/Sao_Paulo

    steps:
      - uses: actions/checkout@v4
      - name: Instalando yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Instalando PlayWright
        run: yarn playwright install
      - name: Testes E2E (end-to-end)
        run: yarn run e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

