# CI de Nível 03 - Disparo atomático sempre que outro for concluído, como deploy

# nome que vai aparecer na execução de pipe
name: 'Execução por Deploy'

# Triggers ou gatilhos de execução
# gatilho de execução após outro workflow = workflow_run
on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

jobs:
  # descrição dos jobs
  e2e-tests:
    # maquina onde vai executar o job
    runs-on: ubuntu-latest
    # passo a passo das ececuções do job
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Instalando yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Instalando PlayWright
        run: yarn playwright install
      - name: Testes E2E (end-to-end)
        run: yarn run e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
