# CI de Nível 04 - Disparo Dentro do fluxo de CI de desenvolvimento

# nome que vai aparecer na execução de pipe
name: 'Execução Integrada'

# Triggers ou gatilhos de execução
# gatilho de execução manual = workflow_dispatch
on:
  workflow_dispatch:
  # inspeção
  #   padronização (formatação de código)
  # testes
  #   unidade
  #   e2e
  #     build
  # deploy
jobs:
  inspection: # descrição do job
    runs-on: ubuntu-latest # maquina onde vai executar o job
    steps: # passo a passo das ececuções do job
      - uses: actions/checkout@v4
      - name: Instalando yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Pronização de código - lint
        run: yarn lint
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando yarn
        run: npm install -g yarn
      - name: Instalando Dependencias
        run: yarn
      - name: Teste de unidade
        run: yarn run test

  e2e-tests: # descrição do job
    runs-on: ubuntu-latest # maquina onde vai executar o job
    steps: # passo a passo das ececuções do job
      - uses: actions/checkout@v4 # precisa fazer chekout do fonte
      - name: Instalando yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Instalando PlayWright
        run: yarn playwright install
      - name: Testes E2E (end-to-end)
        run: yarn run e2e
      # aqui temos a subida de artefato e uso de uma expressão
      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
